//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
namespace ClientWeb.Models

{
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;
    using System.Runtime.Serialization;
    using ServiceReferenceClientWeb;

    [DataContract(IsReference = true)]
    public  class KeywordDTO
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public KeywordDTO()
        {
            this.Files = new List<FileKeywordDTO>();
        }

        [DataMember]
        [Key]
        public int Id { get; set; }

        [DataMember]
        public string Kword { get; set; }

        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        [DataMember]
        public virtual List<FileKeywordDTO> Files { get; set; }
    }
}
