//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Person", Namespace="http://schemas.datacontract.org/2004/07/MemoriesManager", IsReference=true)]
    public partial class Person : object, System.Runtime.Serialization.IExtensibleDataObject
    {
        
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        private MemoriesManager.File[] FilesField;
        
        private string First_nameField;
        
        private int IdField;
        
        private string Last_nameField;
        
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData
        {
            get
            {
                return this.extensionDataField;
            }
            set
            {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public MemoriesManager.File[] Files
        {
            get
            {
                return this.FilesField;
            }
            set
            {
                this.FilesField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string First_name
        {
            get
            {
                return this.First_nameField;
            }
            set
            {
                this.First_nameField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Id
        {
            get
            {
                return this.IdField;
            }
            set
            {
                this.IdField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Last_name
        {
            get
            {
                return this.Last_nameField;
            }
            set
            {
                this.Last_nameField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="File", Namespace="http://schemas.datacontract.org/2004/07/MemoriesManager", IsReference=true)]
    public partial class File : object, System.Runtime.Serialization.IExtensibleDataObject
    {
        
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        private System.DateTime Created_atField;
        
        private int FileIdField;
        
        private MemoriesManager.Keyword[] KeywordsField;
        
        private string LocationField;
        
        private string PathField;
        
        private bool Path_changedField;
        
        private MemoriesManager.Person[] PeopleField;
        
        private string TypeField;
        
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData
        {
            get
            {
                return this.extensionDataField;
            }
            set
            {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime Created_at
        {
            get
            {
                return this.Created_atField;
            }
            set
            {
                this.Created_atField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int FileId
        {
            get
            {
                return this.FileIdField;
            }
            set
            {
                this.FileIdField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public MemoriesManager.Keyword[] Keywords
        {
            get
            {
                return this.KeywordsField;
            }
            set
            {
                this.KeywordsField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Location
        {
            get
            {
                return this.LocationField;
            }
            set
            {
                this.LocationField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Path
        {
            get
            {
                return this.PathField;
            }
            set
            {
                this.PathField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool Path_changed
        {
            get
            {
                return this.Path_changedField;
            }
            set
            {
                this.Path_changedField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public MemoriesManager.Person[] People
        {
            get
            {
                return this.PeopleField;
            }
            set
            {
                this.PeopleField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Type
        {
            get
            {
                return this.TypeField;
            }
            set
            {
                this.TypeField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Keyword", Namespace="http://schemas.datacontract.org/2004/07/MemoriesManager", IsReference=true)]
    public partial class Keyword : object, System.Runtime.Serialization.IExtensibleDataObject
    {
        
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        private MemoriesManager.File[] FilesField;
        
        private int IdField;
        
        private string KwordField;
        
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData
        {
            get
            {
                return this.extensionDataField;
            }
            set
            {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public MemoriesManager.File[] Files
        {
            get
            {
                return this.FilesField;
            }
            set
            {
                this.FilesField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Id
        {
            get
            {
                return this.IdField;
            }
            set
            {
                this.IdField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Kword
        {
            get
            {
                return this.KwordField;
            }
            set
            {
                this.KwordField = value;
            }
        }
    }

[System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
[System.ServiceModel.ServiceContractAttribute(ConfigurationName="IFilePersonKeyword")]
public interface IFilePersonKeyword
{
    
    [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/InterfacePerson/CreatePerson", ReplyAction="http://tempuri.org/InterfacePerson/CreatePersonResponse")]
    bool CreatePerson(MemoriesManager.Person person);
    
    [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/InterfacePerson/CreatePerson", ReplyAction="http://tempuri.org/InterfacePerson/CreatePersonResponse")]
    System.Threading.Tasks.Task<bool> CreatePersonAsync(MemoriesManager.Person person);
    
    [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/InterfacePerson/DeletePerson", ReplyAction="http://tempuri.org/InterfacePerson/DeletePersonResponse")]
    int DeletePerson(int id);
    
    [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/InterfacePerson/DeletePerson", ReplyAction="http://tempuri.org/InterfacePerson/DeletePersonResponse")]
    System.Threading.Tasks.Task<int> DeletePersonAsync(int id);
    
    [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/InterfacePerson/GetAllPeople", ReplyAction="http://tempuri.org/InterfacePerson/GetAllPeopleResponse")]
    MemoriesManager.Person[] GetAllPeople();
    
    [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/InterfacePerson/GetAllPeople", ReplyAction="http://tempuri.org/InterfacePerson/GetAllPeopleResponse")]
    System.Threading.Tasks.Task<MemoriesManager.Person[]> GetAllPeopleAsync();
    
    [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/InterfacePerson/GetPersonByName", ReplyAction="http://tempuri.org/InterfacePerson/GetPersonByNameResponse")]
    MemoriesManager.Person GetPersonByName(string First_name, string Last_name);
    
    [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/InterfacePerson/GetPersonByName", ReplyAction="http://tempuri.org/InterfacePerson/GetPersonByNameResponse")]
    System.Threading.Tasks.Task<MemoriesManager.Person> GetPersonByNameAsync(string First_name, string Last_name);
    
    [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/InterfacePerson/UpdatePerson", ReplyAction="http://tempuri.org/InterfacePerson/UpdatePersonResponse")]
    MemoriesManager.Person UpdatePerson(MemoriesManager.Person newPerson);
    
    [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/InterfacePerson/UpdatePerson", ReplyAction="http://tempuri.org/InterfacePerson/UpdatePersonResponse")]
    System.Threading.Tasks.Task<MemoriesManager.Person> UpdatePersonAsync(MemoriesManager.Person newPerson);
    
    [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/InterfacePerson/UpdatePersonNameById", ReplyAction="http://tempuri.org/InterfacePerson/UpdatePersonNameByIdResponse")]
    MemoriesManager.Person UpdatePersonNameById(int id, string First_name, string Last_name);
    
    [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/InterfacePerson/UpdatePersonNameById", ReplyAction="http://tempuri.org/InterfacePerson/UpdatePersonNameByIdResponse")]
    System.Threading.Tasks.Task<MemoriesManager.Person> UpdatePersonNameByIdAsync(int id, string First_name, string Last_name);
    
    [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/InterfaceKeyword/CreateKeyword", ReplyAction="http://tempuri.org/InterfaceKeyword/CreateKeywordResponse")]
    bool CreateKeyword(MemoriesManager.Keyword keyword);
    
    [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/InterfaceKeyword/CreateKeyword", ReplyAction="http://tempuri.org/InterfaceKeyword/CreateKeywordResponse")]
    System.Threading.Tasks.Task<bool> CreateKeywordAsync(MemoriesManager.Keyword keyword);
    
    [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/InterfaceKeyword/DeleteKeyword", ReplyAction="http://tempuri.org/InterfaceKeyword/DeleteKeywordResponse")]
    int DeleteKeyword(int id);
    
    [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/InterfaceKeyword/DeleteKeyword", ReplyAction="http://tempuri.org/InterfaceKeyword/DeleteKeywordResponse")]
    System.Threading.Tasks.Task<int> DeleteKeywordAsync(int id);
    
    [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/InterfaceKeyword/GetAllKeywords", ReplyAction="http://tempuri.org/InterfaceKeyword/GetAllKeywordsResponse")]
    MemoriesManager.Keyword[] GetAllKeywords();
    
    [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/InterfaceKeyword/GetAllKeywords", ReplyAction="http://tempuri.org/InterfaceKeyword/GetAllKeywordsResponse")]
    System.Threading.Tasks.Task<MemoriesManager.Keyword[]> GetAllKeywordsAsync();
    
    [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/InterfaceKeyword/GetKeywordByKword", ReplyAction="http://tempuri.org/InterfaceKeyword/GetKeywordByKwordResponse")]
    MemoriesManager.Keyword GetKeywordByKword(string Kword);
    
    [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/InterfaceKeyword/GetKeywordByKword", ReplyAction="http://tempuri.org/InterfaceKeyword/GetKeywordByKwordResponse")]
    System.Threading.Tasks.Task<MemoriesManager.Keyword> GetKeywordByKwordAsync(string Kword);
    
    [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/InterfaceKeyword/UpdateKeywordKwordById", ReplyAction="http://tempuri.org/InterfaceKeyword/UpdateKeywordKwordByIdResponse")]
    MemoriesManager.Keyword UpdateKeywordKwordById(int id, string Kword);
    
    [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/InterfaceKeyword/UpdateKeywordKwordById", ReplyAction="http://tempuri.org/InterfaceKeyword/UpdateKeywordKwordByIdResponse")]
    System.Threading.Tasks.Task<MemoriesManager.Keyword> UpdateKeywordKwordByIdAsync(int id, string Kword);
    
    [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/InterfaceFile/CreateFile", ReplyAction="http://tempuri.org/InterfaceFile/CreateFileResponse")]
    bool CreateFile(MemoriesManager.File file);
    
    [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/InterfaceFile/CreateFile", ReplyAction="http://tempuri.org/InterfaceFile/CreateFileResponse")]
    System.Threading.Tasks.Task<bool> CreateFileAsync(MemoriesManager.File file);
    
    [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/InterfaceFile/GetAllFiles", ReplyAction="http://tempuri.org/InterfaceFile/GetAllFilesResponse")]
    MemoriesManager.File[] GetAllFiles();
    
    [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/InterfaceFile/GetAllFiles", ReplyAction="http://tempuri.org/InterfaceFile/GetAllFilesResponse")]
    System.Threading.Tasks.Task<MemoriesManager.File[]> GetAllFilesAsync();
    
    [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/InterfaceFile/DeleteFileByPath", ReplyAction="http://tempuri.org/InterfaceFile/DeleteFileByPathResponse")]
    int DeleteFileByPath(string filePath);
    
    [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/InterfaceFile/DeleteFileByPath", ReplyAction="http://tempuri.org/InterfaceFile/DeleteFileByPathResponse")]
    System.Threading.Tasks.Task<int> DeleteFileByPathAsync(string filePath);
    
    [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/InterfaceFile/GetFileByPath", ReplyAction="http://tempuri.org/InterfaceFile/GetFileByPathResponse")]
    MemoriesManager.File GetFileByPath(string filePath);
    
    [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/InterfaceFile/GetFileByPath", ReplyAction="http://tempuri.org/InterfaceFile/GetFileByPathResponse")]
    System.Threading.Tasks.Task<MemoriesManager.File> GetFileByPathAsync(string filePath);
    
    [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/InterfaceFile/InsertKeywordIntoFile", ReplyAction="http://tempuri.org/InterfaceFile/InsertKeywordIntoFileResponse")]
    void InsertKeywordIntoFile(string kword, string filePath);
    
    [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/InterfaceFile/InsertKeywordIntoFile", ReplyAction="http://tempuri.org/InterfaceFile/InsertKeywordIntoFileResponse")]
    System.Threading.Tasks.Task InsertKeywordIntoFileAsync(string kword, string filePath);
    
    [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/InterfaceFile/GetKeywordsOfFile", ReplyAction="http://tempuri.org/InterfaceFile/GetKeywordsOfFileResponse")]
    MemoriesManager.Keyword[] GetKeywordsOfFile(string filePath);
    
    [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/InterfaceFile/GetKeywordsOfFile", ReplyAction="http://tempuri.org/InterfaceFile/GetKeywordsOfFileResponse")]
    System.Threading.Tasks.Task<MemoriesManager.Keyword[]> GetKeywordsOfFileAsync(string filePath);
    
    [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/InterfaceFile/DeleteKeywordsFromFile", ReplyAction="http://tempuri.org/InterfaceFile/DeleteKeywordsFromFileResponse")]
    void DeleteKeywordsFromFile(int[] keywordsIds, string filePath);
    
    [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/InterfaceFile/DeleteKeywordsFromFile", ReplyAction="http://tempuri.org/InterfaceFile/DeleteKeywordsFromFileResponse")]
    System.Threading.Tasks.Task DeleteKeywordsFromFileAsync(int[] keywordsIds, string filePath);
    
    [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/InterfaceFile/InsertPersonIntoFile", ReplyAction="http://tempuri.org/InterfaceFile/InsertPersonIntoFileResponse")]
    void InsertPersonIntoFile(int personId, string filePath);
    
    [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/InterfaceFile/InsertPersonIntoFile", ReplyAction="http://tempuri.org/InterfaceFile/InsertPersonIntoFileResponse")]
    System.Threading.Tasks.Task InsertPersonIntoFileAsync(int personId, string filePath);
    
    [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/InterfaceFile/GetPeopleFile", ReplyAction="http://tempuri.org/InterfaceFile/GetPeopleFileResponse")]
    MemoriesManager.Person[] GetPeopleFile(string filePath);
    
    [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/InterfaceFile/GetPeopleFile", ReplyAction="http://tempuri.org/InterfaceFile/GetPeopleFileResponse")]
    System.Threading.Tasks.Task<MemoriesManager.Person[]> GetPeopleFileAsync(string filePath);
    
    [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/InterfaceFile/DeletePeopleFromFile", ReplyAction="http://tempuri.org/InterfaceFile/DeletePeopleFromFileResponse")]
    void DeletePeopleFromFile(int[] ids, string filePath);
    
    [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/InterfaceFile/DeletePeopleFromFile", ReplyAction="http://tempuri.org/InterfaceFile/DeletePeopleFromFileResponse")]
    System.Threading.Tasks.Task DeletePeopleFromFileAsync(int[] ids, string filePath);
}

[System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
public interface IFilePersonKeywordChannel : IFilePersonKeyword, System.ServiceModel.IClientChannel
{
}

[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
public partial class FilePersonKeywordClient : System.ServiceModel.ClientBase<IFilePersonKeyword>, IFilePersonKeyword
{
    
    public FilePersonKeywordClient()
    {
    }
    
    public FilePersonKeywordClient(string endpointConfigurationName) : 
            base(endpointConfigurationName)
    {
    }
    
    public FilePersonKeywordClient(string endpointConfigurationName, string remoteAddress) : 
            base(endpointConfigurationName, remoteAddress)
    {
    }
    
    public FilePersonKeywordClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
            base(endpointConfigurationName, remoteAddress)
    {
    }
    
    public FilePersonKeywordClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
            base(binding, remoteAddress)
    {
    }
    
    public bool CreatePerson(MemoriesManager.Person person)
    {
        return base.Channel.CreatePerson(person);
    }
    
    public System.Threading.Tasks.Task<bool> CreatePersonAsync(MemoriesManager.Person person)
    {
        return base.Channel.CreatePersonAsync(person);
    }
    
    public int DeletePerson(int id)
    {
        return base.Channel.DeletePerson(id);
    }
    
    public System.Threading.Tasks.Task<int> DeletePersonAsync(int id)
    {
        return base.Channel.DeletePersonAsync(id);
    }
    
    public MemoriesManager.Person[] GetAllPeople()
    {
        return base.Channel.GetAllPeople();
    }
    
    public System.Threading.Tasks.Task<MemoriesManager.Person[]> GetAllPeopleAsync()
    {
        return base.Channel.GetAllPeopleAsync();
    }
    
    public MemoriesManager.Person GetPersonByName(string First_name, string Last_name)
    {
        return base.Channel.GetPersonByName(First_name, Last_name);
    }
    
    public System.Threading.Tasks.Task<MemoriesManager.Person> GetPersonByNameAsync(string First_name, string Last_name)
    {
        return base.Channel.GetPersonByNameAsync(First_name, Last_name);
    }
    
    public MemoriesManager.Person UpdatePerson(MemoriesManager.Person newPerson)
    {
        return base.Channel.UpdatePerson(newPerson);
    }
    
    public System.Threading.Tasks.Task<MemoriesManager.Person> UpdatePersonAsync(MemoriesManager.Person newPerson)
    {
        return base.Channel.UpdatePersonAsync(newPerson);
    }
    
    public MemoriesManager.Person UpdatePersonNameById(int id, string First_name, string Last_name)
    {
        return base.Channel.UpdatePersonNameById(id, First_name, Last_name);
    }
    
    public System.Threading.Tasks.Task<MemoriesManager.Person> UpdatePersonNameByIdAsync(int id, string First_name, string Last_name)
    {
        return base.Channel.UpdatePersonNameByIdAsync(id, First_name, Last_name);
    }
    
    public bool CreateKeyword(MemoriesManager.Keyword keyword)
    {
        return base.Channel.CreateKeyword(keyword);
    }
    
    public System.Threading.Tasks.Task<bool> CreateKeywordAsync(MemoriesManager.Keyword keyword)
    {
        return base.Channel.CreateKeywordAsync(keyword);
    }
    
    public int DeleteKeyword(int id)
    {
        return base.Channel.DeleteKeyword(id);
    }
    
    public System.Threading.Tasks.Task<int> DeleteKeywordAsync(int id)
    {
        return base.Channel.DeleteKeywordAsync(id);
    }
    
    public MemoriesManager.Keyword[] GetAllKeywords()
    {
        return base.Channel.GetAllKeywords();
    }
    
    public System.Threading.Tasks.Task<MemoriesManager.Keyword[]> GetAllKeywordsAsync()
    {
        return base.Channel.GetAllKeywordsAsync();
    }
    
    public MemoriesManager.Keyword GetKeywordByKword(string Kword)
    {
        return base.Channel.GetKeywordByKword(Kword);
    }
    
    public System.Threading.Tasks.Task<MemoriesManager.Keyword> GetKeywordByKwordAsync(string Kword)
    {
        return base.Channel.GetKeywordByKwordAsync(Kword);
    }
    
    public MemoriesManager.Keyword UpdateKeywordKwordById(int id, string Kword)
    {
        return base.Channel.UpdateKeywordKwordById(id, Kword);
    }
    
    public System.Threading.Tasks.Task<MemoriesManager.Keyword> UpdateKeywordKwordByIdAsync(int id, string Kword)
    {
        return base.Channel.UpdateKeywordKwordByIdAsync(id, Kword);
    }
    
    public bool CreateFile(MemoriesManager.File file)
    {
        return base.Channel.CreateFile(file);
    }
    
    public System.Threading.Tasks.Task<bool> CreateFileAsync(MemoriesManager.File file)
    {
        return base.Channel.CreateFileAsync(file);
    }
    
    public MemoriesManager.File[] GetAllFiles()
    {
        return base.Channel.GetAllFiles();
    }
    
    public System.Threading.Tasks.Task<MemoriesManager.File[]> GetAllFilesAsync()
    {
        return base.Channel.GetAllFilesAsync();
    }
    
    public int DeleteFileByPath(string filePath)
    {
        return base.Channel.DeleteFileByPath(filePath);
    }
    
    public System.Threading.Tasks.Task<int> DeleteFileByPathAsync(string filePath)
    {
        return base.Channel.DeleteFileByPathAsync(filePath);
    }
    
    public MemoriesManager.File GetFileByPath(string filePath)
    {
        return base.Channel.GetFileByPath(filePath);
    }
    
    public System.Threading.Tasks.Task<MemoriesManager.File> GetFileByPathAsync(string filePath)
    {
        return base.Channel.GetFileByPathAsync(filePath);
    }
    
    public void InsertKeywordIntoFile(string kword, string filePath)
    {
        base.Channel.InsertKeywordIntoFile(kword, filePath);
    }
    
    public System.Threading.Tasks.Task InsertKeywordIntoFileAsync(string kword, string filePath)
    {
        return base.Channel.InsertKeywordIntoFileAsync(kword, filePath);
    }
    
    public MemoriesManager.Keyword[] GetKeywordsOfFile(string filePath)
    {
        return base.Channel.GetKeywordsOfFile(filePath);
    }
    
    public System.Threading.Tasks.Task<MemoriesManager.Keyword[]> GetKeywordsOfFileAsync(string filePath)
    {
        return base.Channel.GetKeywordsOfFileAsync(filePath);
    }
    
    public void DeleteKeywordsFromFile(int[] keywordsIds, string filePath)
    {
        base.Channel.DeleteKeywordsFromFile(keywordsIds, filePath);
    }
    
    public System.Threading.Tasks.Task DeleteKeywordsFromFileAsync(int[] keywordsIds, string filePath)
    {
        return base.Channel.DeleteKeywordsFromFileAsync(keywordsIds, filePath);
    }
    
    public void InsertPersonIntoFile(int personId, string filePath)
    {
        base.Channel.InsertPersonIntoFile(personId, filePath);
    }
    
    public System.Threading.Tasks.Task InsertPersonIntoFileAsync(int personId, string filePath)
    {
        return base.Channel.InsertPersonIntoFileAsync(personId, filePath);
    }
    
    public MemoriesManager.Person[] GetPeopleFile(string filePath)
    {
        return base.Channel.GetPeopleFile(filePath);
    }
    
    public System.Threading.Tasks.Task<MemoriesManager.Person[]> GetPeopleFileAsync(string filePath)
    {
        return base.Channel.GetPeopleFileAsync(filePath);
    }
    
    public void DeletePeopleFromFile(int[] ids, string filePath)
    {
        base.Channel.DeletePeopleFromFile(ids, filePath);
    }
    
    public System.Threading.Tasks.Task DeletePeopleFromFileAsync(int[] ids, string filePath)
    {
        return base.Channel.DeletePeopleFromFileAsync(ids, filePath);
    }
}
